export const REGISTER_STEP_ONE = "REGISTER_STEP_ONE";
export const REGISTER_STEP_TWO = "REGISTER_STEP_TWO";
export const LOAD_USER = "LOAD_USER";
export const LOAD_ABOUT = "LOAD_ABOUT";
export const UPLOAD_GALLERY = "UPLOAD_GALLERY";
export const DELETE_GALLERY = "DELETE_GALLERY";
export const UPDATE_GALLERY = "UPDATE_GALLERY";
